package main

import (
	"fmt"
	"html/template"
	"io"
	"strings"
	"unicode"
)

// palette holds the categorical series colors, light and dark.
var palette = [][2]string{
	{"#2a78d6", "#3987e5"}, // blue
	{"#eb6834", "#d95926"}, // orange
	{"#1baf7a", "#199e70"}, // aqua
	{"#eda100", "#c98500"}, // yellow
	{"#e87ba4", "#d55181"}, // magenta
	{"#008300", "#008300"}, // green
	{"#4a3aa7", "#9085e9"}, // violet
	{"#e34948", "#e66767"}, // red
}

func seriesCSS() template.CSS {
	var light, dark, classes strings.Builder
	for i, c := range palette {
		fmt.Fprintf(&light, "--series-%d:%s;", i+1, c[0])
		fmt.Fprintf(&dark, "--series-%d:%s;", i+1, c[1])
		fmt.Fprintf(&classes, ".s%d{fill:var(--series-%[1]d)}.l%[1]d{stroke:var(--series-%[1]d)}.bg%[1]d{background:var(--series-%[1]d)}\n", i+1)
	}
	return template.CSS(fmt.Sprintf(`:root{%s}
@media (prefers-color-scheme: dark){:root:not([data-theme="light"]){%s}}
:root[data-theme="dark"]{%s}
%s`, light.String(), dark.String(), dark.String(), classes.String()))
}

func renderHTML(w io.Writer, pg *page) error {
	return pageTemplate.Execute(w, struct {
		*page
		Series template.CSS
	}{pg, seriesCSS()})
}

// renderMarkdown writes the report as Markdown: charts become tables, with
// text bars and block character sparklines.
func renderMarkdown(w io.Writer, pg *page) error {
	var b strings.Builder
	tiles := func(ts []tile) {
		for _, t := range ts {
			fmt.Fprintf(&b, "- **%s:** %s (%s)\n", mdEsc(t.Label), mdEsc(t.Value), mdEsc(t.Note))
		}
		if len(ts) > 0 {
			b.WriteString("\n")
		}
	}
	fmt.Fprintf(&b, "# %s\n\n%s\n\n", mdEsc(pg.Title), pg.Intro.Markdown())
	tiles(pg.Tiles)
	b.WriteString("Contents:")
	for i, s := range pg.Sections {
		sep := " "
		if i > 0 {
			sep = " · "
		}
		fmt.Fprintf(&b, "%s[%s](#%s)", sep, mdEsc(s.Title), slug(s.Title))
	}
	b.WriteString("\n")
	for _, s := range pg.Sections {
		fmt.Fprintf(&b, "\n## %s\n\n", mdEsc(s.Title))
		for _, p := range s.Lead {
			b.WriteString(p.Markdown() + "\n\n")
		}
		tiles(s.Tiles)
		for _, bl := range s.Blocks {
			if bl.Title != "" {
				fmt.Fprintf(&b, "### %s\n\n", mdEsc(bl.Title))
			}
			if bl.Subtitle != "" {
				fmt.Fprintf(&b, "*%s*\n\n", mdEsc(bl.Subtitle))
			}
			for _, f := range bl.Figs {
				b.WriteString(f.Markdown() + "\n")
			}
			for _, c := range bl.Cards {
				fmt.Fprintf(&b, "- **%s** (%s):", mdEsc(c.Title), mdEsc(c.Kicker))
				if body := c.Body.Markdown(); body != "" {
					b.WriteString(" " + body)
				}
				if c.Spark != nil {
					fmt.Fprintf(&b, " `%s`", blockSpark(c.Spark.Values))
				}
				if c.Note != "" {
					b.WriteString(" " + mdEsc(c.Note))
				}
				b.WriteString("\n")
			}
			if len(bl.Cards) > 0 {
				b.WriteString("\n")
			}
			for _, n := range bl.Notes {
				b.WriteString(n.Markdown() + "\n\n")
			}
		}
	}
	b.WriteString("\n---\n\n")
	for _, n := range pg.Notes {
		b.WriteString(n.Markdown() + "\n\n")
	}
	b.WriteString("Generated by leurisreport.\n")
	_, err := io.WriteString(w, b.String())
	return err
}

// slug returns the anchor that Markdown renderers like GitHub derive from a
// heading.
func slug(s string) string {
	var b strings.Builder
	for _, r := range strings.ToLower(s) {
		switch {
		case unicode.IsLetter(r) || unicode.IsDigit(r) || r == '-' || r == '_':
			b.WriteRune(r)
		case r == ' ':
			b.WriteByte('-')
		}
	}
	return b.String()
}

var pageTemplate = template.Must(template.New("page").Parse(`<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>{{.Title}}</title>
<style>
:root {
  color-scheme: light;
  --page: #f9f9f7; --surface: #fcfcfb; --ink: #0b0b0b; --ink-2: #52514e; --muted: #898781;
  --grid: #e1e0d9; --axis: #c3c2b7; --border: rgba(11,11,11,0.10); --hover: rgba(11,11,11,0.05);
  --mark-muted: #c3c2b7; --link: #1c5cab;
}
@media (prefers-color-scheme: dark) {
  :root:not([data-theme="light"]) {
    color-scheme: dark;
    --page: #0d0d0d; --surface: #1a1a19; --ink: #ffffff; --ink-2: #c3c2b7; --muted: #898781;
    --grid: #2c2c2a; --axis: #383835; --border: rgba(255,255,255,0.10); --hover: rgba(255,255,255,0.06);
    --mark-muted: #52514e; --link: #86b6ef;
  }
}
:root[data-theme="dark"] {
  color-scheme: dark;
  --page: #0d0d0d; --surface: #1a1a19; --ink: #ffffff; --ink-2: #c3c2b7; --muted: #898781;
  --grid: #2c2c2a; --axis: #383835; --border: rgba(255,255,255,0.10); --hover: rgba(255,255,255,0.06);
  --mark-muted: #52514e; --link: #86b6ef;
}
{{.Series}}
* { box-sizing: border-box; }
body { margin: 0; background: var(--page); color: var(--ink); font: 15px/1.55 system-ui, -apple-system, "Segoe UI", sans-serif; }
main { max-width: 1040px; margin: 0 auto; padding: 32px 16px 64px; }
a { color: var(--link); text-decoration: none; }
a:hover { text-decoration: underline; }
h1 { font-size: 30px; line-height: 1.2; margin: 0 0 8px; letter-spacing: -0.01em; }
h2 { font-size: 22px; margin: 56px 0 8px; padding-top: 8px; border-top: 1px solid var(--grid); }
h3 { font-size: 15px; margin: 0; }
.intro { color: var(--ink-2); max-width: 70ch; margin: 0 0 24px; }
.lead { max-width: 75ch; color: var(--ink-2); }
nav { display: flex; flex-wrap: wrap; gap: 4px 16px; font-size: 14px; margin: 0 0 24px; }
.tiles { display: grid; grid-template-columns: repeat(auto-fit, minmax(180px, 1fr)); gap: 12px; margin: 16px 0 8px; }
.tile { background: var(--surface); border: 1px solid var(--border); border-radius: 8px; padding: 12px 14px; }
.tile .label { color: var(--ink-2); font-size: 13px; }
.tile .value { font-size: 26px; font-weight: 600; line-height: 1.25; }
.tile .note { color: var(--muted); font-size: 12px; }
.blocks { display: grid; grid-template-columns: 1fr 1fr; gap: 16px; margin-top: 16px; }
.block { grid-column: 1 / -1; background: var(--surface); border: 1px solid var(--border); border-radius: 8px; padding: 16px; min-width: 0; }
.block.half { grid-column: auto; }
@media (max-width: 760px) { .blocks { grid-template-columns: 1fr; } .block.half { grid-column: 1 / -1; } }
.sub { color: var(--ink-2); font-size: 13px; margin: 2px 0 12px; }
.bnote { color: var(--muted); font-size: 12px; margin: 10px 0 0; }
svg.chart { width: 100%; height: auto; display: block; overflow: visible; }
svg text { font: 11px system-ui, -apple-system, "Segoe UI", sans-serif; }
.tick { fill: var(--muted); font-variant-numeric: tabular-nums; }
.endlabel { fill: var(--ink-2); font-variant-numeric: tabular-nums; }
.grid { stroke: var(--grid); stroke-width: 1; shape-rendering: crispEdges; }
.base { stroke: var(--axis); stroke-width: 1; shape-rendering: crispEdges; }
.muted { fill: var(--mark-muted); }
.line { fill: none; stroke-width: 2; stroke-linejoin: round; stroke-linecap: round; }
.dot { stroke: var(--surface); stroke-width: 2; }
.wash { fill: var(--series-1); opacity: 0.1; }
.hit { fill: transparent; }
.hit:hover { fill: var(--hover); }
.legend { display: flex; flex-wrap: wrap; gap: 4px 14px; font-size: 13px; color: var(--ink-2); margin: 0 0 8px; }
.legend span { display: inline-flex; align-items: center; gap: 6px; }
.sw { display: inline-block; width: 10px; height: 10px; border-radius: 3px; }
.hbars { display: grid; gap: 6px; }
.hb { display: grid; grid-template-columns: minmax(0, 15em) 1fr; gap: 10px; align-items: center; font-size: 13px; }
.hb:hover { background: var(--hover); border-radius: 4px; }
.hb-l { overflow-wrap: anywhere; line-height: 1.3; }
.hb-l small { color: var(--muted); }
.hb-t { display: flex; align-items: center; gap: 6px; min-width: 0; }
.hb-t i { display: block; height: 14px; border-radius: 0 4px 4px 0; min-width: 2px; }
.hb-t span { color: var(--ink-2); font-variant-numeric: tabular-nums; white-space: nowrap; }
@media (max-width: 520px) { .hb { grid-template-columns: 1fr; gap: 2px; } }
.spark { display: block; overflow: visible; }
.spark .line { stroke-width: 1.5; }
.tablewrap { overflow-x: auto; }
table { border-collapse: collapse; width: 100%; font-size: 13px; }
th, td { text-align: left; padding: 6px 8px; border-bottom: 1px solid var(--grid); vertical-align: middle; }
th { color: var(--ink-2); font-weight: 600; white-space: nowrap; }
.num { text-align: right; font-variant-numeric: tabular-nums; white-space: nowrap; }
.ibar { display: inline-block; width: 60px; height: 8px; margin-right: 8px; vertical-align: middle; }
.ibar i { display: block; height: 100%; border-radius: 0 4px 4px 0; min-width: 2px; }
td:has(.ibar) { white-space: nowrap; font-variant-numeric: tabular-nums; }
.gantt { font-size: 12px; }
.g-row { display: grid; grid-template-columns: minmax(0, 17em) 1fr; gap: 10px; align-items: center; padding: 2px 0; }
.g-row:not(.g-axis):hover { background: var(--hover); border-radius: 4px; }
.g-l { white-space: nowrap; overflow: hidden; text-overflow: ellipsis; }
.g-l small { color: var(--muted); }
.g-t { position: relative; height: 14px; }
.g-t i { position: absolute; top: 2px; height: 10px; border-radius: 4px; min-width: 3px; }
.g-t .now { position: absolute; top: -2px; bottom: -2px; width: 1px; background: var(--axis); }
.g-axis .g-t span { position: absolute; transform: translateX(-50%); color: var(--muted); font-variant-numeric: tabular-nums; }
@media (max-width: 520px) { .g-row { grid-template-columns: 8em 1fr; } .g-l small { display: none; } }
.cards { display: grid; grid-template-columns: repeat(auto-fill, minmax(260px, 1fr)); gap: 12px; }
.card { border: 1px solid var(--border); border-radius: 8px; padding: 12px 14px; background: var(--surface); }
.blocks .block .card { background: transparent; }
.kicker { color: var(--muted); font-size: 12px; text-transform: uppercase; letter-spacing: 0.04em; }
.card p { margin: 6px 0 0; font-size: 14px; color: var(--ink-2); }
.card .spark { margin: 8px 0 4px; }
.cardnote { display: block; font-size: 12px; color: var(--muted); }
.block.bare { background: none; border: 0; padding: 0; }
details.data { margin-top: 8px; font-size: 13px; }
details.data summary { cursor: pointer; color: var(--ink-2); width: fit-content; }
details.data .tablewrap { max-height: 320px; overflow-y: auto; margin-top: 6px; }
footer { margin-top: 56px; color: var(--muted); font-size: 13px; }
footer p { max-width: 80ch; }
.tip { position: fixed; left: 0; top: 0; z-index: 10; pointer-events: none; opacity: 0; max-width: 340px;
  background: var(--surface); color: var(--ink); border: 1px solid var(--border); border-radius: 6px;
  padding: 6px 9px; font-size: 12px; line-height: 1.45; white-space: pre-line; box-shadow: 0 2px 10px rgba(0,0,0,0.12);
  font-variant-numeric: tabular-nums; }
</style>
</head>
<body>
<main>
<header>
<h1>{{.Title}}</h1>
<p class="intro">{{.Intro.HTML}}</p>
<nav>{{range .Sections}}<a href="#{{.ID}}">{{.Title}}</a>{{end}}</nav>
</header>
<div class="tiles">{{range .Tiles}}<div class="tile"><div class="label">{{.Label}}</div><div class="value">{{.Value}}</div><div class="note">{{.Note}}</div></div>{{end}}</div>
{{range .Sections}}
<section id="{{.ID}}">
<h2>{{.Title}}</h2>
{{range .Lead}}<p class="lead">{{.HTML}}</p>{{end}}
{{if .Tiles}}<div class="tiles">{{range .Tiles}}<div class="tile"><div class="label">{{.Label}}</div><div class="value">{{.Value}}</div><div class="note">{{.Note}}</div></div>{{end}}</div>{{end}}
<div class="blocks">
{{range .Blocks}}<div class="block{{if .Half}} half{{end}}{{if and .Cards (not .Title)}} bare{{end}}">
{{if .Title}}<h3>{{.Title}}</h3>{{end}}
{{if .Subtitle}}<p class="sub">{{.Subtitle}}</p>{{end}}
{{range .Figs}}{{.HTML}}{{end}}
{{if .Cards}}<div class="cards">{{range .Cards}}<div class="card"><div class="kicker">{{.Kicker}}</div><h3>{{.Title}}</h3>{{with .Body.HTML}}<p>{{.}}</p>{{end}}{{with .Spark}}{{.HTML}}{{end}}{{with .Note}}<span class="cardnote">{{.}}</span>{{end}}</div>{{end}}</div>{{end}}
{{range .Notes}}<p class="bnote">{{.HTML}}</p>{{end}}
</div>
{{end}}
</div>
</section>
{{end}}
<footer>
{{range .Notes}}<p>{{.HTML}}</p>{{end}}
<p>Generated by leurisreport.</p>
</footer>
</main>
<script>
(() => {
  const tip = document.createElement("div");
  tip.className = "tip";
  document.body.appendChild(tip);
  let shown = null;
  document.addEventListener("pointermove", (e) => {
    const t = e.target instanceof Element ? e.target.closest("[data-tip]") : null;
    if (!t) { tip.style.opacity = 0; shown = null; return; }
    if (t !== shown) { tip.textContent = t.getAttribute("data-tip"); shown = t; }
    const r = tip.getBoundingClientRect();
    let x = e.clientX + 14, y = e.clientY + 14;
    if (x + r.width > innerWidth - 8) x = e.clientX - r.width - 14;
    if (y + r.height > innerHeight - 8) y = e.clientY - r.height - 14;
    tip.style.transform = "translate(" + Math.max(8, x) + "px," + Math.max(8, y) + "px)";
    tip.style.opacity = 1;
  });
  document.addEventListener("pointerleave", () => { tip.style.opacity = 0; shown = null; });
})();
</script>
</body>
</html>
`))
